### ISSUE TITLE
Can't override default instance attributes

### ISSUE THREAD

**Issue by szymonpk** [fewbytes-cookbooks/redis2#7]
Code I've used

<pre>node.set.redis2.instances.prime.vm.max_memory = '512mb'
node.set.redis2.instances.prime.maxmemory_policy = 'allkeys-lru'

include_recipe 'redis2::default_instance'</pre>

Result 

<pre># grep 512 /etc/redis/redis_prime.conf
list-max-ziplist-entries 512
set-max-intset-entries 512</pre>

I've also tried overwrite with `node.default`, doesn't work either.

**Comment by nukemberg** [comment]
these values are hardcoded in [the template](https://github.com/fewbytes-cookbooks/redis2/blob/master/templates/default/redis.conf.erb#L403). We should probably move these to attributes

**Comment by szymonpk** [comment]
Erm... sorry you got this wrong. I'm trying to set max_memory to 512 and only 512 values I've found were these two default mentioned above.

<pre># grep maxmemory /etc/redis/redis_prime.conf
# WARNING: maxmemory can be a good idea mainly if you want to use Redis as a
# to upgrade. With maxmemory after the limit is reached you'll start to get
# MAXMEMORY POLICY: how Redis will select what to remove when maxmemory
# maxmemory-samples 3</pre>

My max_memory override isn't applied.

**Comment by szymonpk** [comment]
Forget about this issue, I've used wrong keys. With these two below everything works fine:

<pre>node.set.redis2.instances.prime.maxmemory = '512mb'
node.set.redis2.instances.prime.maxmemory_policy = 'allkeys-lru'</pre>

It just wasn't documented.
